name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Create bin folder
      run: mkdir bin
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: '3.5.x'
    - name: Restore NuGet Packages
      run: nuget restore Bonsai.sln
    - name: Build solution
      run: msbuild Bonsai.sln /p:Configuration=Release
    
